### ISSUE TITLE
Multi-tenant (channels) to support /[hash]/battle and /[hash] so different groups can have their own battles

### ISSUE THREAD

**Issue by bpark08** [mmccaff/giphy-battle#2]

**Comment by mmccaff** [comment]
I started this by setting up the routes for channels and refactoring to be able to share the route handlers between the current root channel routes and user specified channel routes.

What's ahead:

Anything Socket.io needs to change to use rooms or namespaces
http://socket.io/docs/rooms-and-namespaces/

Anything accessing MongoDB is going to need to use a new channel attribute in the document.

**Comment by mmccaff** [comment]
This is done. There is now support for ad hoc channels (rooms) to emerge like this:

Main (aka general):
/
/battle
/favorites

Anything else:
/anything
/anything/battle
/anything/favorites
... where 'anything' is the name of the room and can be anything.

This allows for multiple battles so that different companies, groups etc can use it at once to have their own separate displays and battles controlling those displays.

**Comment by bpark08** [comment]
Would you be open to changing "anything" to "custom"?

**Comment by mmccaff** [comment]
The word 'anything' was just used in my description to denote any dynamic,
variable word in the url that creates a channel aka room. It is not an
actual hard-coded string. So for example, if sales wanted to have their own
battle, they could just load up

/sales on the TV, and battle on
/sales/battle

Their favorites would be /sales/favorites and of course 'sales' could just
as easily be 'marketing', 'livingroom', etc to be in a different channel.

Just the act of going to a URL like that makes it be namespaced into its
own non-root room.

Matt
